# brainome/examples docker-compose for launching a jupyter notebook instance with brainome's examples
#
version: '3.1'

services:
  brainome_tutorials:
    container_name: brainome_jupyter
    image: brainome/jupyter:latest
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 1234:8888
    volumes:
      - '.:/work'

