# jupyterbook build and publish to s3

name: jupyterbook

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  # This workflow contains a single job called "build"
  build:
    # jupyterbook
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: install jupyterbook et al.
        run: python3 -m pip install -r requirements.txt

      - name: build jupyterbook
        run: |
          jupyter-book build . --keep-going --all

      # https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: publish to s3 jupyter.brainome.ai
        run: |
          cd _build/html
          aws s3 sync . s3://jupyter.brainome.ai

      - name: clean up btc install
        if: always()
        run: |
          sudo rm -rf ~/.daimensions.key .daimensions.key /usr/local/brainome /usr/local/bin/btc *.bat *.sh *.exe
